### ISSUE TITLE
Index out of bound exception in HtmlTable$Row.getColumn. Build 20161106

### ISSUE THREAD

**Issue by rud0x7b6** [unclebob/fitnesse#1036]
In one of our tests we have this error. I downloaded latest version from github, added callstack printing during exceptions and had got listing 1(see below). It caused by additional empty column in test sorce code like this(line 3 - "||"):
|query:Get Card Tasks By Reg Card|seodoserver  |${TestPrefix}${TestIndex}                                                                                                                             |
|Регистрационный Номер           |Исполнитель  |Тип назначенного|Контроль   |Состояние       |Автор        |Текст задания       |Тип                 |Срок исполнения|Происхождение карточки|
|${TestPrefix}${TestIndex1}      |fit Ваньян   |Responsible     |Yes        |Исполнено       |fit Говорунов|Тест Тест пункт1    |Поручение           |01.05.2112     ||
|${TestPrefix}${TestIndex1}      |fit Гарсиа   |Coexecutor      |Yes        |Исполнено       |fit Говорунов|Тест Тест пункт1    |Поручение           |01.05.2112     |       

Note, that BUILD fitnesse-standalone20140418.jar  can correct parse this case (we had no any problems in our tests with old version 20140418).
"Out of bound" exception is present in fitnesse-standalone20140623.jar and all following builds.

LISTING 1
Caused by: java.lang.IndexOutOfBoundsException: Index: 10, Size: 10
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at fitnesse.testsystems.slim.HtmlTable$Row.getColumn(HtmlTable.java:256)
        at fitnesse.testsystems.slim.HtmlTable.getCellContents(HtmlTable.java:74)
        at fitnesse.testsystems.slim.tables.QueryTable$QueryResults$QueryMatcher.scoreMatch(QueryTable.java:308)
        at fitnesse.testsystems.slim.tables.QueryTable$QueryResults$QueryMatcher.scoreMatches(QueryTable.java:292)
        at fitnesse.testsystems.slim.tables.QueryTable$QueryResults.scorePotentialMatches(QueryTable.java:260)
        at fitnesse.testsystems.slim.tables.QueryTable.scanRowsForMatches(QueryTable.java:96)
        at fitnesse.testsystems.slim.tables.QueryTable.access$000(QueryTable.java:17)
        at fitnesse.testsystems.slim.tables.QueryTable$QueryTableExpectation.evaluateExpectation(QueryTable.java:75)
        at fitnesse.testsystems.slim.SlimTestSystem.evaluateTables(SlimTestSystem.java:149)
        at fitnesse.testsystems.slim.SlimTestSystem.processTable(SlimTestSystem.java:127)
        at fitnesse.testsystems.slim.HtmlSlimTestSystem.processAllTablesOnPage(HtmlSlimTestSystem.java:56)
        at fitnesse.testsystems.slim.SlimTestSystem.runTests(SlimTestSystem.java:89)

**Comment by woodybrood** [comment]
Closing this. Looking at it, I think that this table was missing a column in the last row.
