### ISSUE TITLE
An error occured while fulfilling user request [fitnesse.http.HttpException: The request string is malformed and can not be parsed]

### ISSUE THREAD

**Issue by janakijayasree** [unclebob/fitnesse#1042]
An error occured while fulfilling user request [fitnesse.http.HttpException: The request string is malformed and can not be parsed]
java.util.concurrent.ExecutionException: fitnesse.http.HttpException: The request string is malformed and can not be parsed
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at fitnesse.FitNesseExpediter.makeResponse(FitNesseExpediter.java:105)
        at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:58)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: fitnesse.http.HttpException: The request string is malformed and can not be parsed
        at fitnesse.http.Request.checkRequestLine(Request.java:159)
        at fitnesse.http.Request.readAndParseRequestLine(Request.java:73)
        at fitnesse.http.Request.parse(Request.java:61)
        at fitnesse.FitNesseExpediter$1.call(FitNesseExpediter.java:102)
        at fitnesse.FitNesseExpediter$1.call(FitNesseExpediter.java:99)
        ... 4 more
getting this error after using java -jar fitnesse-standalone.jar -p 8088 in cmd.
unble to connect to local host showing 0 fail 0 pass....in test page..
please help me how to solve this..i am using latest version of fitnesse-standalone.jar

**Comment by jediwhale** [comment]
We should include the invalid request string in the exception message - would make these easier to diagnose...

**Comment by Zordid** [comment]
Got the same problem here. Hosting FitNesse on Azure as a Java application. But whenever I access it, this is the message I see in the log. What can be wrong with "the request string"? What is that anyhow? I simply go to the root URL of my server, exactly like I do on localhost on a local machine...
