### ISSUE TITLE
Java 9 Compatibility: New Default System ClassLoader

### ISSUE THREAD

**Issue by InspiredIdealist** [unclebob/fitnesse#1092]
I noticed that the `fitnesse.components.PluginsClassLoader` assumes that the `ClassLoader.getSystemClassLoader()` is the type `java.net.URLClassLoader`. This is fine for versions of Java up to 9 -- since as of Java 9, [it is now a jdk.internal.loader.ClassLoaders$AppClassLoader apparently](https://blog.codefx.org/java/java-9-migration-guide/#Casting-To-URL-Class-Loader).

I get the following error upon startup (causing FitNesse to crash):

```
SEVERE: Error while starting the FitNesse [java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader]
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at fitnesse.components.PluginsClassLoader.addUrlToClasspath(PluginsClassLoader.java:39)
        at fitnesse.components.PluginsClassLoader.addFileToClassPath(PluginsClassLoader.java:35)
        at fitnesse.components.PluginsClassLoader.addItemsToClasspath(PluginsClassLoader.java:30)
        at fitnesse.components.PluginsClassLoader.addPluginsToClassLoader(PluginsClassLoader.java:21)
        at fitnesseMain.FitNesseMain.loadPlugins(FitNesseMain.java:122)
        at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:63)
        at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:58)
        at fitnesseMain.FitNesseMain.main(FitNesseMain.java:38)
```

**Comment by amolenaar** [comment]
I was looking into this. It's only applicable if you have plugins installed in the `plugins` folder.

I wonder: could we just get rid of this plugins folder altogether? If you want to do fancy stuff with plugins, use a tool for handling that, such as Gradle or Maven.

**Comment by InspiredIdealist** [comment]
So what this would have the effect of is only allowing loading plugins via the FitNesse classpath, correct? I'd be fine with that!

**Comment by fhoeben** [comment]
The plugins folder is nice for creating 'standalone' installations (with plugins loaded); where people don't need to have Gradle or Maven (or even a JDK) to run a local wiki to execute tests.
If the functionality can't be kept: too bad, but I would really like to keep it. 

We could at least do a quick fix to prevent FitNesse from crashing, and instead just log an error on Java9 that plugins are disabled. But ideally the mechanism would be kept.

**Comment by fhoeben** [comment]
Could an alternative be adding `Class-Path: plugins/*` (or `Class-Path: plugins:plugins/*`) to the manifest of fitnesse-standalone.jar? Or does that mechanism also no longer work in Java 9?

**Comment by fhoeben** [comment]
So now I learned that one cannot use wildcards in manifests. 
But a message indicating the problem is nicer that just failing on a cast... I'll see whether I can create a pull request for that.

**Comment by fhoeben** [comment]
I created a branch where on Java 9 I get the following message (with 2 jars in the plugins folder):
```
WARNING: Unable to add plugin to classpath. Are you running Java 9? Please ensure you add the required plugins to the wiki's classpath through other means.
WARNING: Unable to extend classpath to include plugin: /Users/fried/dev/hsac-fitnesse-fixtures/wiki/plugins/maven-classpath-plugin-1.9-jar-with-dependencies.jar
WARNING: Unable to extend classpath to include plugin: /Users/fried/dev/hsac-fitnesse-fixtures/wiki/plugins/hsac-fitnesse-plugin-1.18.4-SNAPSHOT.jar
SEVERE: Error while starting the FitNesse [Unable to load class fitnesse.wikitext.widgets.MavenClasspathSymbolType]
fitnesse.plugins.PluginException: Unable to load class fitnesse.wikitext.widgets.MavenClasspathSymbolType
	at fitnesse.plugins.PropertyBasedPluginFeatureFactory.forName(PropertyBasedPluginFeatureFactory.java:200)
	at fitnesse.plugins.PropertyBasedPluginFeatureFactory.forEachClass(PropertyBasedPluginFeatureFactory.java:143)
	at fitnesse.plugins.PropertyBasedPluginFeatureFactory.forEachObject(PropertyBasedPluginFeatureFactory.java:150)
	at fitnesse.plugins.PropertyBasedPluginFeatureFactory.registerSymbolTypes(PropertyBasedPluginFeatureFactory.java:75)
	at fitnesse.plugins.PluginsLoader.loadSymbolTypes(PluginsLoader.java:87)
	at fitnesse.ContextConfigurator.makeFitNesseContext(ContextConfigurator.java:151)
	at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:69)
	at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:58)
	at fitnesseMain.FitNesseMain.main(FitNesseMain.java:38)
Caused by: java.lang.ClassNotFoundException: fitnesse.wikitext.widgets.MavenClasspathSymbolType
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:292)
	at fitnesse.plugins.PropertyBasedPluginFeatureFactory.forName(PropertyBasedPluginFeatureFactory.java:198)
	... 8 more
[ERROR] Command execution failed.
```

Still, not really what I would like to have. But a bit better....

**Comment by amolenaar** [comment]
> Could an alternative be adding Class-Path: plugins/* (or Class-Path: plugins:plugins/*) to the manifest of fitnesse-standalone.jar? Or does that mechanism also no longer work in Java 9?

That may be worth a try.

**Comment by amolenaar** [comment]
Hmm.. Maybe load the classes in a separate class loader (using the current class loader as parent) and pass that class loader to `ServiceLoader.load` and the plugin loader logic.

**Comment by fhoeben** [comment]
A separate class loader is probably what we really need. Implementing that is probably a bit bigger task. I thought we could start by at least having a nicer message, and allow FitNesse to be used with Java 9 _if_ one takes care of adding the plugins to the classpath oneself.
