### ISSUE TITLE
Some remote exceptions in the system under test cause a unhelpful "java.lang.AssertionError: null" to be reported by the JUnitRunNotifierResultsListener

### ISSUE THREAD

**Issue by lestephane** [unclebob/fitnesse#1134]
Hey guys, i'm a long time user of Fitnesse, and came across this problem a few times.

It's a bit tricky to describe, but I'll do my best, because others might have come across it, and have been confused as to what's going on.  I've searched the issues for __java.lang.AssertionError: null__ and came up empty. So here it goes.

I get the following in the junit output windows when running a fitnesse test suite (through the HsacFitnesseRunner in this example):

```
java.lang.AssertionError: null

	at fitnesse.junit.JUnitRunNotifierResultsListener.firstFailure(JUnitRunNotifierResultsListener.java:149)
	at fitnesse.junit.JUnitRunNotifierResultsListener.testExceptionOccurred(JUnitRunNotifierResultsListener.java:83)
	at fitnesse.testsystems.CompositeTestSystemListener.testExceptionOccurred(CompositeTestSystemListener.java:61)
	at fitnesse.testrunner.MultipleTestsRunner$InternalTestSystemListener.testExceptionOccurred(MultipleTestsRunner.java:220)
	at fitnesse.testsystems.CompositeTestSystemListener.testExceptionOccurred(CompositeTestSystemListener.java:61)
	at fitnesse.testsystems.slim.SlimTestSystem.testExceptionOccurred(SlimTestSystem.java:196)
	at fitnesse.testsystems.slim.SlimTestSystem.evaluateTables(SlimTestSystem.java:148)
	at fitnesse.testsystems.slim.SlimTestSystem.processTable(SlimTestSystem.java:130)
	at fitnesse.testsystems.slim.HtmlSlimTestSystem.processAllTablesOnPage(HtmlSlimTestSystem.java:56)
	at fitnesse.testsystems.slim.SlimTestSystem.runTests(SlimTestSystem.java:92)
	at fitnesse.testrunner.MultipleTestsRunner.executeTestSystemPages(MultipleTestsRunner.java:158)
	at fitnesse.testrunner.MultipleTestsRunner.startTestSystemAndExecutePages(MultipleTestsRunner.java:78)
	at fitnesse.testrunner.MultipleTestsRunner.internalExecuteTestPages(MultipleTestsRunner.java:66)
	at fitnesse.testrunner.MultipleTestsRunner.executeTestPages(MultipleTestsRunner.java:49)
	at fitnesse.junit.FitNesseRunner.executeTests(FitNesseRunner.java:481)
	at fitnesse.junit.FitNesseRunner.runPages(FitNesseRunner.java:403)
	at nl.hsac.fitnesse.junit.HsacFitNesseRunner.runPages(HsacFitNesseRunner.java:212)
	at fitnesse.junit.FitNesseRunner.run(FitNesseRunner.java:384)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

Which is not very informative, so i went into the debugger. The actual error information is available in the _JUnitRunNotifierResultsListener.testExceptionOccurred_ stack frame, within the ExceptionResult argument's exceptionValue field:

```
__EXCEPTION__:java.lang.ClassNotFoundException: <span class="meta">undefined variable: database.driverClassName</span>
	at java.lang.Class.forName0(Native Method) [rt.jar:1.8.0_161]
	at java.lang.Class.forName(Class.java:264) [rt.jar:1.8.0_161]
	at com.acme.fixtures.integration_tests.SetupDatabaseConnection.executeOnce(SetupDatabaseConnection.java:39) [file:/home/lestephane/GitRepos/eventide-audio-services-java/eventide-services/target/test-classes/]
	at com.acme.fixtures.SingleActionFixture.execute(SingleActionFixture.java:30) [file:/project/target/classes/]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_161]
	at fitnesse.slim.fixtureInteraction.DefaultInteraction.methodInvoke(DefaultInteraction.java:221) [fitnesse-20180127.jar:20180127]
	at fitnesse.slim.fixtureInteraction.DefaultInteraction.callMethod(DefaultInteraction.java:206) [fitnesse-20180127.jar:20180127]
	at fitnesse.slim.fixtureInteraction.DefaultInteraction.invokeMethod(DefaultInteraction.java:188) [fitnesse-20180127.jar:20180127]
	at fitnesse.slim.fixtureInteraction.DefaultInteraction.findAndInvoke(DefaultInteraction.java:166) [fitnesse-20180127.jar:20180127]
	at fitnesse.slim.MethodExecutor.findAndInvoke(MethodExecutor.java:18) [fitnesse-20180127.jar:20180127]
	at fitnesse.slim.FixtureMethodExecutor.execute(FixtureMethodExecutor.java:18) [fitnesse-20180127.jar:20180127]
	at fitnesse.slim.StatementExecutor.getMethodExecutionResult(StatementExecutor.java:139) [fitnesse-20180127.jar:20180127]
	at fitnesse.slim.StatementExecutor.call(StatementExecutor.java:112) [fitnesse-20180127.jar:20180127]
	at fitnesse.slim.instructions.CallInstruction.executeInternal(CallInstruction.java:35) [fitnesse-20180127.jar:20180127]
	at fitnesse.slim.instructions.Instruction.execute(Instruction.java:29) [fitnesse-20180127.jar:20180127]
	at fitnesse.slim.ListExecutor$Executive.executeStatement(ListExecutor.java:49) [fitnesse-20180127.jar:20180127]
	at fitnesse.slim.ListExecutor$Executive.executeStatements(ListExecutor.java:43) [fitnesse-20180127.jar:20180127]
	at fitnesse.slim.ListExecutor.execute(ListExecutor.java:85) [fitnesse-20180127.jar:20180127]
	at fitnesse.slim.SlimServer.executeInstructions(SlimServer.java:82) [fitnesse-20180127.jar:20180127]
	at fitnesse.slim.SlimServer.processOneSetOfInstructions(SlimServer.java:75) [fitnesse-20180127.jar:20180127]
	at fitnesse.slim.SlimServer.tryProcessInstructions(SlimServer.java:62) [fitnesse-20180127.jar:20180127]
	at fitnesse.slim.SlimServer.serve(SlimServer.java:47) [fitnesse-20180127.jar:20180127]
	at fitnesse.testsystems.slim.InProcessSlimClient$1.run(InProcessSlimClient.java:55) [fitnesse-20180127.jar:20180127]
	at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_161]
```

But testExceptionOccurred only propagates the ExceptionResult's getMessage() string (which returns _null_).
If testExceptionOccured would propagate ExceptionResult's getException() instead (when getMessage() == _null_), one would get the full 'remote' stack trace of the system-under-test, and the person running the test would get more meaningful feedback, instead of having to wip up a debugger, and go one stack frame deeper.

I propose in JUnitRunNotifierResultsListener.testExceptionOccurred(Assertion assertion, ExceptionResult exceptionResult), that if ExceptionResult.getMessage() is __null__, Exception.getException() be used, with the fitnesse framework stack frames removed / filtered. This would be in our case:

```
 __EXCEPTION__:java.lang.ClassNotFoundException: <span class="meta">undefined variable: database.driverClassName</span>
	at java.lang.Class.forName0(Native Method) [rt.jar:1.8.0_161]
	at java.lang.Class.forName(Class.java:264) [rt.jar:1.8.0_161]
	at com.acme.fixtures.integration_tests.SetupDatabaseConnection.executeOnce(SetupDatabaseConnection.java:39) [file:/home/lestephane/GitRepos/eventide-audio-services-java/eventide-services/target/test-classes/]
	at com.acme.fixtures.SingleActionFixture.execute(SingleActionFixture.java:30) [file:/project/target/classes/]
```

Does it sound like a change for the better? I've created an issue in the fitnesse project because that's where __fitnesse.junit.JUnitRunNotifierResultsListener.testExceptionOccurred__ is located.

**Comment by fhoeben** [comment]
I would have to look into more detail to see whether the jUnit message can indeed be better. It sounds like a good suggestion.

In general I don't really look at the exceptions when running tests with the HsacFitNesseRunner. I just want to see red/green for each test. I will then look at the generated HTML page for the specific test that failed/threw an exception. I find that to much more informative as it shows: the context the error happened, any other problems found by the test and FULL details of the exceptions encountered

**Comment by fhoeben** [comment]
But even in a headless CI environment the HTML files still get generated, right? You might have to do some extra work to get them stored somewhere where you can access them after the run. 

I have set that up in a Travis CI environment where I push the HTML reports to a git repo after a run. 

But that could, of course, very easily be something like an S3 bucket which I assume would not be very hard from CodeBuild.

**Comment by lestephane** [comment]
@fhoeben Until you run your test suite in a headless CI environment like CodeBuild.

**Comment by lestephane** [comment]
I've spent a lot of time reporting the problem, and I proposed the solution. Asking me to add more logic on my end to a CloudFormation template to work around a limitation in Fitnesse has its limits. Not everyone in a team understands cloudformation. Not every company has a 'cloudformation person'. But everyone will understand *undefined variable: database.driverClassName*, if if were to be output on standard output or standard error. I got the error obfuscation problem often enough, that I created this issue. And I'm glad it's getting some feedback, 6 months later.

**Comment by fhoeben** [comment]
@lestephane, I'm not a maintainer of FitNesse and I believe I understand your problem. I was just trying to help by sharing how I deal with this lack of information and suggest how the approach that works for me might be usable in your situation...

**Comment by lestephane** [comment]
@fhoeben Sorry I got carried out. I love the HsacFitnesseRunner, so no gripe against you. Is this a Hsac limitation or Fitnesse limitation?

The added step of packing the html test run report to a human reachable location might be too much for most people running a CI/CD pipeline, presenting an additional barrier to adoption of an otherwise great framework.

**Comment by fhoeben** [comment]
It's a FitNesse thing (although I have to admit I have worked on PRs changing the FitNesse `JUnitRunNotifierResultsListener`).
I agree it's an extra barrier, but the readable (detailed, not just first failure) HTML reports are one of the most valuable features of the framework. In my opinion it is worth the extra effort.

Are you running the tests directly from Maven/Gradle, or are you using docker images (like the ones I published) to run the tests.

**Comment by lestephane** [comment]
So far it's maven only.

**Comment by fhoeben** [comment]
On a platform like CloudFormation running based on docker images is quite nice, there is no need to download dependencies and compile stuff, just grab the docker image and run the test (and publish the results ;-)).

**Comment by lestephane** [comment]
This does not invalidate my issue, but please do say more about how to use your docker image (link?), and what you use to 'publish' the results (cloudformation template, bash script...). This would help while waiting for an upstream fix from the Fitnesse team.

**Comment by fhoeben** [comment]
I created two images, one with just FitNesse & my fixtures and one with FitNesse, my fixtures and Selenium node running chrome: https://hub.docker.com/r/hsac/fitnesse-fixtures-test-jre8/ and https://hub.docker.com/r/hsac/fitnesse-fixtures-test-jre8-chrome/

I hope their READMEs provide some insight on how to use them.

How to publish your results depends a lot on the environment you run your tests. I have no personal experience with CloudBuild/CloudFormation. I often run the tests in a client's environment using Jenkins/TeamCity/Bamboo which offer standard features to publish 'artefacts' and a directory with HTML files fits into their definitions nicely. For my fixture project I use Travis-CI, where I push the directory with results back to GitHub using a [shell script](https://github.com/fhoeben/hsac-fitnesse-fixtures/blob/master/travis_publish_results.sh). The script first clones a (separate) repo, deletes the current content, copies the html results of the last run into the directory, commits the new/current content and pushes that back to GitHub. 

For CloudBuild a quick google brought me a couple of articles on how to publish a static website to S3, and the test report is just a static website after all. So for instance https://dzone.com/articles/continuous-delivery-to-s3-via-codepipeline-and-cod seems to describe a pipeline which pushes some Artifacts to S3 (in its 'Deploy' action), in the case of a FitNesse run I would call the generated HTML report (in `/target/fitnesse-results`) the output artifacts of the test run/action, which would serve as input artifact to a deploy action. I don't know how this fits in your current setup, but it seems quite straightforward once the permissions in the IAM Role and the bucket have been created.

But we are straying quite a bit from the original issue :-) Maybe this is more suited for [my fixture's sample project](https://github.com/fhoeben/sample-fitnesse-project), or the [project for the docker images](https://github.com/fhoeben/hsac-fitnesse-docker)?

**Comment by lestephane** [comment]
Thanks for the additional information. That will help for now, but the
issue still remains.
