### ISSUE TITLE
FitNesse stopping if suite exceeds ~ 1 hour

### ISSUE THREAD

**Issue by Deuskull** [unclebob/fitnesse#1140]
Hello.
I have a suite of multiple suites which is equivalent to 7500 tests (each one different for a really big application).
When I launch the big suite in my remote Fitnesse, it stopped at ~ 2500 tests (every test work independently). It took ~ 1 hour.
When I launch the suite from the server, java -jar fitnesse-standalone.jar -c "MyBigSuite?suite&format=text", it fails after ~ 1 hour too.

I have to launch the big suite every night. Is there a timeout somewhere which blocks the Fitnesse suite if too long (didn't find one in the doc) ? 
Is this a bug ?

Regards

**Comment by amolenaar** [comment]
Hi,

Apart from the fact that I oppose against long running suites (since they do not provide feedback), have you checked why the tests break down? Is the Fit/Slim process running out of memory? Is Fitnesse itself running out of memory? Do you have any logging to suppose diagnosing your issue?

Regards,

Arjan

**Comment by jediwhale** [comment]
As a workaround, you can try running a series of jobs for the overnight run:
java -jar fitnesse-standalone.jar -c "MyFirstSuite?suite&format=text"
java -jar fitnesse-standalone.jar -c "MySecondSuite?suite&format=text"
etc

**Comment by Deuskull** [comment]
Hi.
I finally get the error after ~ 1h30 of testing :
Exception in thread "CommandRunner stdOut" java.lang.OutOfMemoryError: Requested array size exceeds VM limit
        at java.util.Arrays.copyOf(Arrays.java:3332)
        at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
        at java.lang.StringBuffer.append(StringBuffer.java:272)
        at  fitnesse.reporting.history.ExecutionReport$ExecutionLogReport.addStdOut(ExecutionReport.java:240)
        at fitnesse.reporting.history.ExecutionReport.addStdOut(ExecutionReport.java:203)
        at fitnesse.reporting.history.SuiteHistoryFormatter.stdOut(SuiteHistoryFormatter.java:162)
        at fitnesse.testsystems.CompositeExecutionLogListener.stdOut(CompositeExecutionLogListener.java:27)
        at fitnesse.testsystems.ClientBuilder$DecoratingExecutionLogListener.stdOut(ClientBuilder.java:215)
        at fitnesse.testsystems.CommandRunner$1.write(CommandRunner.java:75)
        at fitnesse.testsystems.CommandRunner$OutputReadingRunnable.run(CommandRunner.java:220)
        at java.lang.Thread.run(Thread.java:745)

@amolenaar Sorry but I wasn't able to properly get the error. It's an OutOfMemory unfortunately as above.
I understand that long running suites are not common but we have a very large project and we want to launch our 7500 tests every night to see if no one has broken something during the day. We still have a small subset during each build.

@jediwhale 
Thanks. It may be a solution if we can't solve the OutOfMemory.

I will try to increase the Xmx and I may use some arguments like that -XX:+UseCompressedOops for the moment

**Comment by violinner** [comment]
The FitNesse captures the test process stdOut & stdErr.  The FitNesse report writer uses an in-memory formatter for test results reporting.  The amount of memory required expands exponentially to the amount of console output captured from the tests.

It is likely that your tests emit enough console output to break the FitNesse report formatter, i.e., the "Execution Log."

The solution is to write all test console output to a logger, i.e., slf4j, and configure a log writer, i.e., logback, to write nothing to the console, and all output to a rolling log file.

All that should appear in the execution log should be the classpath logger, log severity & log file location.

**Comment by woodybrood** [comment]
Going to close this. @jediwhale my experience years ago supports your recommendation. Really big suites just aren't a great idea. When my team let things get too big, the system slowed down, a lot. @violinner Your suggestion helps as well.
