### ISSUE TITLE
How to debug - Unable to start test system 'slim': fitnesse.slim.SlimError: Error SLiM server startup failed.

### ISSUE THREAD

**Issue by Subbu13** [unclebob/fitnesse#1147]
Getting this error - Unable to start test system 'slim': fitnesse.slim.SlimError: Error SLiM server startup failed.
how to fix this? 

Have defined slim and the class path as -
!define TEST_SYSTEM {slim}
!define slim.port {0}
!path C:\fitnesse

**Comment by baisakhroy** [comment]
Heyy, I too am getting the same error. Did you resolve it somehow?

**Comment by tcnh** [comment]
Are you using Java 10? Slim server won't start using Java 10

Op di 18 sep. 2018 07:42 schreef baisakhroy <notifications@github.com>:

**Comment by jinlxz** [comment]
Hi, I have this issues too, it threw the following trace stack.
```java
java.net.SocketException: Software caused connection abort: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
	at fitnesse.FitNesseExpediter.send(FitNesseExpediter.java:70)
	at fitnesse.http.ChunkedResponse.closeTrailer(ChunkedResponse.java:75)
	at fitnesse.http.ChunkedResponse.close(ChunkedResponse.java:82)
	at fitnesse.responders.run.SuiteResponder.closeHtmlResponse(SuiteResponder.java:362)
	at fitnesse.responders.run.SuiteResponder.doSending(SuiteResponder.java:125)
	at fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:74)
	at fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:27)
	at fitnesse.FitNesseExpediter.sendResponse(FitNesseExpediter.java:93)
	at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
do you know how to fix it?

**Comment by essenius** [comment]
I had the same error as the initial poster, and for me it was caused by an incorrect value of the JAVA_HOME environment variable. Correcting the value (or removing the variable) resolved the issue for me.

**Comment by fhoeben** [comment]
It could be many things.

- How did you start FitNesse?
- What does you classpath and slim configuration look like (in wiki)?
- What is shown in the console output?
- What is shown when you open the Execution Log (the button on top of page after you tried running the test)?

**Comment by mohitbisht578** [comment]
Hi,
1. How did you start FitNesse? - I have started through runFitness.bat file
it runner successfully after that I put localhost address and type the wiki
page.

2. What does you classpath and slim configuration look like (in wiki)? - I
have given the path of eclipse code .class file

3.What is shown when you open the Execution Log (the button on top of page
after you tried running the test - it is giving me unable to start test
system slim:fitness.slim.SlimError

Please help me to solve this problem

Thanks,
Mohit

**Comment by naimishranderi** [comment]
I had the same error. I could fix it when I removed two entries from Environmental Variable > Path  

C:\Program Files (x86)\Common Files\Oracle\Java\javapath
C:\Program Files\Common Files\Oracle\Java\javapath
