### ISSUE TITLE
Git plugin does not work well with FitNesse > 20180127

### ISSUE THREAD

**Issue by fhoeben** [unclebob/fitnesse#1181]
As reported on the mailing list by reprive23

I am still encountering the same behavior, also with FitNesse 20190119. It works well if I put the plugins explicitly in the classpath, I get the following error if I start with java -jar.
```
SEVERE: Error while starting the FitNesse [Unable to instantiate component for type fitnesse.wiki.fs.FileSystemPageFactory]
fitnesse.components.ComponentInstantiationException: Unable to instantiate component for type fitnesse.wiki.fs.FileSystemPageFactory
        at fitnesse.components.ComponentFactory.createComponent(ComponentFactory.java:81)
        at fitnesse.components.ComponentFactory.createComponent(ComponentFactory.java:57)
        at fitnesse.components.ComponentFactory.createComponent(ComponentFactory.java:100)
        at fitnesse.ContextConfigurator.makeFitNesseContext(ContextConfigurator.java:107)
        at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:72)
        at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:59)
        at fitnesseMain.FitNesseMain.main(FitNesseMain.java:39)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
        at fitnesse.components.ComponentFactory.createComponent(ComponentFactory.java:75)
        ... 6 more
Caused by: fitnesse.components.ComponentInstantiationException: Unable to look up component for type 'VersionsController' with classname 'fitnesse.wiki.fs.GitFileVersionsController'
        at fitnesse.components.ComponentFactory.createComponent(ComponentFactory.java:53)
        at fitnesse.components.ComponentFactory.createComponent(ComponentFactory.java:100)
        at fitnesse.wiki.fs.FileSystemPageFactory.<init>(FileSystemPageFactory.java:36)
        ... 11 more
Caused by: java.lang.ClassNotFoundException: fitnesse.wiki.fs.GitFileVersionsController
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        at fitnesse.components.ComponentFactory.lookupComponentClass(ComponentFactory.java:96)
        at fitnesse.components.ComponentFactory.createComponent(ComponentFactory.java:49)
        ... 13 more
```

**Comment by fhoeben** [comment]
I tracked down the cause of this problem: the `FileSystemPageFactory` tries to load the plugin, and it does so using the system standard class loader and not the class loader created by FitNesse which includes the .jars in the plugins directory (because it creates its own ComponentFactory instead of using the one that is created already).
