### ISSUE TITLE
LongConverter is throwing NullPointerException on returning null 

### ISSUE THREAD

**Issue by aquddos123** [unclebob/fitnesse#1211]
We are using SliM decision table and recently upgraded FitNesse from release 20161106 to 20190416. 

We use to have getters with return type "int" and "long" working fine when null is returned. 
But after this version upgrade we started seeing NullPointerException for null objects returned as long. See below Exception details. 

I can see discussion in #363 and #686 to convert null objects into "null" but they are very old discussions. Are there any new changes made to SliM Converter after 20161106 release?

__EXCEPTION__:java.lang.NullPointerException
at fitnesse.slim.converters.LongConverter.toString(LongConverter.java:7) [fitnesse-20190416.jar:20190416]
at fitnesse.slim.converters.LongConverter.toString(LongConverter.java:5) [fitnesse-20190416.jar:20190416]
at fitnesse.slim.MethodExecutionResult.toString(MethodExecutionResult.java:94) [fitnesse-20190416.jar:20190416]
at fitnesse.slim.MethodExecutionResult.returnValue(MethodExecutionResult.java:85) [fitnesse-20190416.jar:20190416]
at fitnesse.slim.StatementExecutor.call(StatementExecutor.java:112) [fitnesse-20190416.jar:20190416]
at fitnesse.slim.instructions.CallInstruction.executeInternal(CallInstruction.java:35) [fitnesse-20190416.jar:20190416]
at fitnesse.slim.instructions.Instruction.execute(Instruction.java:29) [fitnesse-20190416.jar:20190416]
at fitnesse.slim.ListExecutor$Executive.executeStatement(ListExecutor.java:49) [fitnesse-20190416.jar:20190416]
at fitnesse.slim.ListExecutor$Executive.executeStatements(ListExecutor.java:43) [fitnesse-20190416.jar:20190416]
at fitnesse.slim.ListExecutor.execute(ListExecutor.java:85) [fitnesse-20190416.jar:20190416]
at fitnesse.slim.SlimServer.executeInstructions(SlimServer.java:82) [fitnesse-20190416.jar:20190416]
at fitnesse.slim.SlimServer.processOneSetOfInstructions(SlimServer.java:75) [fitnesse-20190416.jar:20190416]
at fitnesse.slim.SlimServer.tryProcessInstructions(SlimServer.java:62) [fitnesse-20190416.jar:20190416]
at fitnesse.slim.SlimServer.serve(SlimServer.java:47) [fitnesse-20190416.jar:20190416]
at fitnesse.slim.SlimService.handle(SlimService.java:169) [fitnesse-20190416.jar:20190416]
at fitnesse.slim.SlimService.acceptOne(SlimService.java:177) [fitnesse-20190416.jar:20190416]
at fitnesse.slim.SlimService.accept(SlimService.java:139) [fitnesse-20190416.jar:20190416]
at fitnesse.slim.SlimService.startWithFactory(SlimService.java:92) [fitnesse-20190416.jar:20190416]
at fitnesse.slim.SlimService.main(SlimService.java:57) [fitnesse-20190416.jar:20190416]

**Comment by fhoeben** [comment]
I believe that the behaviour for `Long` objects was indeed changed in #602 

The conversion does indeed not seem null safe. Seems quite easy to fix, other converters are ok.

As a workaround you could (temporary) register your own converter for longs...

```
public class LongConverter implements Converter<Long> {
  public String toString(Long o) {
    return o != null ? o.toString() : NULL_VALUE;
  }

  public Long fromString(String arg) {
    return Long.parseLong(arg);
  }
}
```

**Comment by aquddos123** [comment]
Sorry I mistakenly closed.

**Comment by aquddos123** [comment]
@fhoeben what do you mean by "**temporarily**" register a converter. Is this feature going to change again in near future?

**Comment by fhoeben** [comment]
i expect to release a fixed version soon....

**Comment by aquddos123** [comment]
Thanks @fhoeben.
