### ISSUE TITLE
Redirect/303 after creating symlink with 'Run a Rest Command'

### ISSUE THREAD

**Issue by royvanrijn** [unclebob/fitnesse#1223]
I'm trying to update a very old project using `20140901` to the latest Fitnesse `20190428`.

The build pipeline of this project runs a REST command to create a symlink:
`-c FrontPage?responder=symlink&linkName=name&linkPath=location`

This used to work fine in `20140901`  because the single command returned a 200 page.

The latest version however returns a 303/redirect and it seems that running a Rest Command with `-c` does not support redirects because we get the following response:
````
     [java] Executing command: FrontPage?responder=symlink&linkName=name&linkPath=location
     [java] SEVERE: Error while starting the FitNesse [error loading page: 303]
     [java] java.lang.Exception: error loading page: 303
     [java] 	at fitnesse.FitNesse.executeSingleCommand(FitNesse.java:68)
     [java] 	at fitnesseMain.FitNesseMain.executeSingleCommand(FitNesseMain.java:177)
     [java] 	at fitnesseMain.FitNesseMain.launch(FitNesseMain.java:129)
     [java] 	at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:97)
     [java] 	at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:59)
     [java] 	at fitnesseMain.FitNesseMain.main(FitNesseMain.java:39)
```` 

Is there any way to add a symlink without getting redirected? 

This stops me from being able to upgrade at the moment.

**Comment by fhoeben** [comment]
I don't believe the behaviour of the symbolic link responder has changed, but the handling of the response returned by the `FitNesse` class has. Before 063b7cbe41c4056f33de944c70feecf1adc3ef22 it ignored the response status from the responder and later it requires a 200 or will throw an exception otherwise.

That was introduced to handle 404 responses from the SuiteResponder when the page being executed did not exist.

Let me see whether we can check for a 4xx or 5xx status and throw an exception then, instead of requiring 200.
