### ISSUE TITLE
I got an exception error when trying to run a test suite by tags filter

### ISSUE THREAD

**Issue by nguyentuanviet77** [unclebob/fitnesse#1239]
Hi all,

I'm trying to run a test that use tags filter following the guide in Fitness page [http://fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.WritingAcceptanceTests.TestSuites.TagsAndFilters](http://fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.WritingAcceptanceTests.TestSuites.TagsAndFilters) but it throughs an exception error.

I use the URL similar this http://<host>:<port>/<suite path and test name>?responder=suite&runTestsMatchingAnyTag=smoke 

And the exception error is like below:
WARNING: An error occured while fulfilling user request [No responder for properties?edit]
java.lang.InstantiationException: No responder for properties?edit
        at fitnesse.responders.ResponderFactory.lookupResponder(ResponderFactory.java:151)
        at fitnesse.responders.ResponderFactory.makeResponder(ResponderFactory.java:129)
        at fitnesse.FitNesseExpediter.createGoodResponse(FitNesseExpediter.java:143)
        at fitnesse.FitNesseExpediter.makeResponse(FitNesseExpediter.java:112)
        at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:51)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

Is this the FitNesse issue?

Thanks,
Viet

**Comment by tcnh** [comment]
Looking at the exception, I'd say your url ends with `?properties?edit` instead of the URL you described. Could you double check if you're using the right url? (Without properties or edit in the parameters)

**Comment by nguyentuanviet77** [comment]
> Looking at the exception, I'd say your url ends with `?properties?edit` instead of the URL you described. Could you double check if you're using the right url? (Without properties or edit in the parameters)

Hi,
I have check my URL, it was not a proprieties or edit, it was http://localhost:8089/FrontPage.SuiteSompoIndo.SompoTestCases?responder=suite&runTestsMatchingAnyTag=Agent

Agent is my filter tag

Thanks,
Viet

**Comment by fhoeben** [comment]
I'm unable to reproduce the problem.
Can you try to create a small suite exhibiting this problem that you can share with us?
