### ISSUE TITLE
[Question]Got "OSError: [WinError 10048]" when try to run test

### ISSUE THREAD

**Issue by Napol-lersuwanich** [unclebob/fitnesse#1413]
Hi, I follow these instructions to try to run a test using python,
https://medium.com/@a_bhi_9/using-fitnesse-s-slim-protocol-to-write-functional-tests-in-python-b4cfb195b821
and 
https://stackoverflow.com/questions/31991135/using-slim-to-write-fitnesse-tests-using-python

both lead me to the same error, "OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted"

this is the full log, 

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\waferslim-1.0.2-py3.11.egg\waferslim\server.py", line 164, in <module>
    start_server()
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\waferslim-1.0.2-py3.11.egg\waferslim\server.py", line 161, in start_server
    WaferSlimServer(options).serve_forever()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\waferslim-1.0.2-py3.11.egg\waferslim\server.py", line 86, in __init__
    super().__init__(server_address, SlimRequestHandler)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\socketserver.py", line 456, in __init__
    self.server_bind()
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\socketserver.py", line 472, in server_bind
    self.socket.bind(self.server_address)
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

any ideas how to solve this error, been searching the solution for days, Thank you.

**Comment by fhoeben** [comment]
I don't know Python, but the error code suggests that more than one program is trying to listen on the same socket. Any chance you have multiple slim servers running at the same time (or another program already using the port number you supply). I believe this will not be the port number supplied to FitNesse but to 'waferslim'.

**Comment by fhoeben** [comment]
A quick glance at the source of 'waferslim' suggests a port number needs to be supplied as command line argument to waferslim that argument is your problem I believe (I don't know what value you are supplying, but 8080 is a bad choice if FitNesse is running on that)

**Comment by Napol-lersuwanich** [comment]
> 

thanks, will look into it.
