### ISSUE TITLE
The filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by konstantinvlasenko** [unclebob/fitnesse#381]
Found in [Last stable build](https://cleancoder.ci.cloudbees.com/job/fitnesse/lastStableBuild/)
OS: Windows

Unpacking new version of FitNesse resources. Please be patient...

---

Files have been updated to a new version.
Please read the release notes on
http://localhost:8081/FitNesse.ReleaseNotes
to find out about the new features and fixes.

---

WARNING: Unable to handle request [The filename, directory name, or volume label syntax is incorrect]
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
        at java.io.WinNTFileSystem.canonicalize0(Native Method)
        at java.io.Win32FileSystem.canonicalize(Unknown Source)
        at java.io.File.getCanonicalPath(Unknown Source)
        at java.io.File.getCanonicalFile(Unknown Source)
        at fitnesse.responders.files.FileResponder.isInFilesDirectory(FileResponder.java:170)
        at fitnesse.responders.files.FileResponder.makeResponder(FileResponder.java:48)
        at fitnesse.responders.ResponderFactory.makeResponder(ResponderFactory.java:135)
        at fitnesse.FitNesseExpediter.createGoodResponse(FitNesseExpediter.java:126)
        at fitnesse.FitNesseExpediter.makeResponse(FitNesseExpediter.java:108)
        at fitnesse.FitNesseExpediter.start(FitNesseExpediter.java:49)
        at fitnesse.FitNesseServer.serve(FitNesseServer.java:28)
        at fitnesse.FitNesseServer.serve(FitNesseServer.java:21)
        at fitnesse.socketservice.SocketService$ServerRunner.run(SocketService.java:101)
        at java.lang.Thread.run(Unknown Source)

**Comment by lo-rodriguez** [comment]
As you can close if the problem is perceived, I do the same with windows 10 and throw the same exception as discussed in the thread.
