### ISSUE TITLE
Installation fails on windows if path to fitnesse-standalone.jar contains spaces

### ISSUE THREAD

**Issue by gberche-orange** [unclebob/fitnesse#418]
I am reporting this fairly common problem with java programs on windows, in hope that it will get indexed by google and save next windows fitnesse users a bit of time if ever they forget this windows trap.

A fix might be to add quotes around the path to the fitnesse-standalone.jar in the system.exec command.

When running fitnesses on windows, the test hangs and eventually displays the following trace after a few minutes:

```
c:\code>"C:\Program Files\Java\jdk1.7.0_25\bin\java" -jar "C:\My Program Files\fitnesse-standalone.jar"
[...]
Output stream closed unexpectedly (Stop button pressed?) [Software caused connection abort: socket write error]
Output stream closed unexpectedly (Stop button pressed?) [Software caused connection abort: socket write error]

WARNING: error registered in test system [Error connecting to SLiM server on localhost:8087]
fitnesse.slim.SlimError: Error connecting to SLiM server on localhost:8087
        at fitnesse.testsystems.slim.SlimCommandRunningClient.tryConnect(SlimCommandRunningClient.java:103)
[...]
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at java.net.Socket.connect(Socket.java:528)
        at java.net.Socket.<init>(Socket.java:425)
        at java.net.Socket.<init>(Socket.java:208)
        at fitnesse.testsystems.slim.SlimCommandRunningClient.tryConnect(SlimCommandRunningClient.java:100)
        ... 234 more
```

you'll find verbose traces into `...`\FitNesseRoot\ErrorLogs\FitNesse\UserGuide\TwoMinuteExample\content.txt`  indicating the executed command which hints that it lacks quotes around the executed java command

```
!3 !-slim:fitnesse.slim.SlimService-!
|'''Date: '''| 4:31:17 PM (CET) on mercredi, mars 12, 2014 |
|'''Test Page: '''|.FitNesse.UserGuide.TwoMinuteExample|
|'''Command: '''| !-java -cp C:\My Program Files\fitnesse-standalone.jar;classes;lib/*.jar fitnesse.slim.SlimService  8087-! |
|'''Exit code: '''| 1 |
|'''Time elapsed: '''| 210.321 seconds |

----
'''Standard Error:'''
{{{ Erreur : impossible de trouver ou charger la classe principale Program
 }}}
```

**Comment by magmax** [comment]
Problem still happening with version 20151230 in Windows.

Here you have an example accessing to the fitnesse-standalone.jar in current path:
```
C:\tmp\fitnesse\jar>java -jar fitnesse.jar -c "/FitNesse.UserGuide.TwoMinuteExample?test&format=text"
ene 20, 2016 2:08:06 PM fitnesse.ConfigurationParameter loadProperties
INFO: No configuration file found (C:\tmp\fitnesse\jar\plugins.properties)
Bootstrapping FitNesse, the fully integrated standalone wiki and acceptance testing framework.
root page: fitnesse.wiki.fs.FileSystemPage at .\FitNesseRoot#latest
logger: none
authenticator: fitnesse.authentication.PromiscuousAuthenticator
page factory: fitnesse.html.template.PageFactory
page theme: bootstrap
Unpacking new version of FitNesse resources. Please be patient...
**********************************************************
Files have been updated to a new version.
Please read the release notes on
http://localhost:9123/FitNesse.ReleaseNotes
to find out about the new features and fixes.
**********************************************************
Executing command: /FitNesse.UserGuide.TwoMinuteExample?test&format=text

Starting Test System: slim:fitnesse.slim.SlimService.
F 14:08:15 R:5    W:1    I:0    E:0    TwoMinuteExample (FitNesse.UserGuide.TwoMinuteExample)   0,51
6 seconds
--------
1 Tests,        1 Failures      1,303 seconds.
```

and here accessing from the parent path:

```
C:\tmp\fitnesse>java -jar jar\fitnesse.jar -c "/FitNesse.UserGuide.TwoMinuteExample?test&format=text"
ene 20, 2016 2:09:06 PM fitnesse.ConfigurationParameter loadProperties
INFO: No configuration file found (C:\tmp\fitnesse\plugins.properties)
Bootstrapping FitNesse, the fully integrated standalone wiki and acceptance testing framework.
root page: fitnesse.wiki.fs.FileSystemPage at .\FitNesseRoot#latest
logger: none
authenticator: fitnesse.authentication.PromiscuousAuthenticator
page factory: fitnesse.html.template.PageFactory
page theme: bootstrap
Unpacking new version of FitNesse resources. Please be patient...
**********************************************************
Files have been updated to a new version.
Please read the release notes on
http://localhost:9123/FitNesse.ReleaseNotes
to find out about the new features and fixes.
**********************************************************
Executing command: /FitNesse.UserGuide.TwoMinuteExample?test&format=text
--------
0 Tests,        0 Failures      1,345 seconds.
```

As you can appreciate, both examples are equal, but the second one doesn't work. By executing them from the web interface, the result is a message showing:

```
Testing was interrupted and results are incomplete. Test Pages: 0 right, 0 wrong, 0 ignored, 0 exceptions     Assertions: 0 right, 0 wrong, 0 ignored, 0 exceptions (1,511 seconds)
Could not complete testing: fitnesse.slim.SlimError: Error SLiM server died before a connection could be established. Error: Could not find or load main class fitnesse.slim.SlimService
```

Maybe I'm doing something wrong?
