### ISSUE TITLE
The filename, directory name, or volume label syntax is incorrect (Windows)

### ISSUE THREAD

**Issue by konstantinvlasenko** [unclebob/fitnesse#434]
Environment: Windows 2012
[Fitnesse 20140201](http://fitnesse.org/.FrontPage.FitNesseDevelopment.FitNesseRelease20140201)
Fitnesse run command: java -jar fitnesse-standalone.jar -d c:\fitnesse -p 8081

To reproduce: Click on Test and check Fitnesse console output.
How it affects me?: seems it doesn't affect me at all:) Test continues.

I believe I've posted this issue previously. Probably at Pivotal Tracker. I can't find it right now. I just want to confirm again that I still having this issue below:

> WARNING: Unable to handle request [The filename, directory name, or volume label syntax is incorrect]
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
        at java.io.WinNTFileSystem.canonicalize0(Native Method)
        at java.io.Win32FileSystem.canonicalize(Unknown Source)
        at java.io.File.getCanonicalPath(Unknown Source)
        at java.io.File.getCanonicalFile(Unknown Source)
        at fitnesse.responders.files.FileResponder.isInFilesDirectory(FileResponder.java:170)
        at fitnesse.responders.files.FileResponder.makeResponder(FileResponder.java:48)
        at fitnesse.responders.ResponderFactory.makeResponder(ResponderFactory.java:146)
        at fitnesse.FitNesseExpediter.createGoodResponse(FitNesseExpediter.java:126)
        at fitnesse.FitNesseExpediter.makeResponse(FitNesseExpediter.java:108)
        at fitnesse.FitNesseExpediter.start(FitNesseExpediter.java:49)
        at fitnesse.FitNesseServer.serve(FitNesseServer.java:28)
        at fitnesse.FitNesseServer.serve(FitNesseServer.java:21)
        at fitnesse.socketservice.SocketService$ServerRunner.run(SocketService.java:110)
        at java.lang.Thread.run(Unknown Source)

**Comment by amolenaar** [comment]
Closing issue, please reopen if action needs to be taken.
