### ISSUE TITLE
error registered in test system

### ISSUE THREAD

**Issue by maxstreichert** [unclebob/fitnesse#512]
Hello,
since release 20130530 fitnesse does not run Slim C++ tests, showing the exception (see below).
These are my global variables:
variable defined: TEST_SYSTEM=slim 
variable defined: TEST_RUNNER=../../bin/TestFitnesse.exe 
variable defined: COMMAND_PATTERN=%m

If I start FitNesse (v20121220), the test run properly. So what's wrong?

Thanks in advance
Max

WARNING: error registered in test system [Stream closed]
java.io.IOException: Stream closed
        at java.io.BufferedWriter.ensureOpen(Unknown Source)
        at java.io.BufferedWriter.write(Unknown Source)
        at java.io.Writer.write(Unknown Source)
        at fitnesse.testsystems.slim.SlimCommandRunningClient.writeString(SlimCommandRunningClient.java:205)
        at fitnesse.testsystems.slim.SlimCommandRunningClient.invokeAndGetResponse(SlimCommandRunningClient.java:134)
        at fitnesse.testsystems.slim.SlimTestSystem.processTable(SlimTestSystem.java:123)
        at fitnesse.testsystems.slim.HtmlSlimTestSystem.processAllTablesOnPage(HtmlSlimTestSystem.java:51)
        at fitnesse.testsystems.slim.SlimTestSystem.runTests(SlimTestSystem.java:100)
        at fitnesse.testrunner.MultipleTestsRunner.executeTestSystemPages(MultipleTestsRunner.java:173)
        at fitnesse.testrunner.MultipleTestsRunner.startTestSystemAndExecutePages(MultipleTestsRunner.java:101)
        at fitnesse.testrunner.MultipleTestsRunner.internalExecuteTestPages(MultipleTestsRunner.java:86)
        at fitnesse.testrunner.MultipleTestsRunner.executeTestPages(MultipleTestsRunner.java:68)
        at fitnesse.responders.run.TestResponder.performExecution(TestResponder.java:273)
        at fitnesse.responders.run.TestResponder.doExecuteTests(TestResponder.java:121)
        at fitnesse.responders.run.TestResponder$TestExecutor.execute(TestResponder.java:205)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:395)
        at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:384)
        at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:173)
        at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:280)
        at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:369)
        at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
        at org.apache.velocity.runtime.directive.Parse.render(Parse.java:260)
        at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
        at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
        at org.apache.velocity.Template.merge(Template.java:356)
        at org.apache.velocity.Template.merge(Template.java:260)
        at fitnesse.html.template.HtmlPage.render(HtmlPage.java:81)
        at fitnesse.responders.run.TestResponder.doSending(TestResponder.java:107)
        at fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:70)
        at fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:25)
        at fitnesse.FitNesseExpediter.sendResponse(FitNesseExpediter.java:100)
        at fitnesse.FitNesseExpediter.start(FitNesseExpediter.java:51)
        at fitnesse.FitNesseServer.serve(FitNesseServer.java:28)
        at fitnesse.FitNesseServer.serve(FitNesseServer.java:21)
        at fitnesse.socketservice.SocketService$ServerRunner.run(SocketService.java:110)
        at java.lang.Thread.run(Unknown Source)

**Comment by caiofbpa** [comment]
I'm getting the `java.io.IOException: Stream closed` when trying to set FitNesse up with WaferSlim (Python).

**Comment by guillaume-humbert** [comment]
Got the same issue as well.
It was caused because for one query table, the headers and the columns were not in sync (i.e. I had 7 headers for 6 columns of data).
Removing the additional header made it work.
