### ISSUE TITLE
Invocation of method 'getTestResult' in  class fitnesse.reporting.history.SuiteXmlReformatter threw exception java.lang.NullPointerException

### ISSUE THREAD

**Issue by konstantinvlasenko** [unclebob/fitnesse#514]
Hi All,
I have this issue if I run my suite trough command line **-c**  ?...**&format=xml**.

>  -----Command Output-----
> <?xml version="1.0"?>
> <testResults>
>   <FitNesseVersion>v20140630</FitNesseVersion>
>   <rootPath>XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX</rootPath>
>     <result>
>     <counts>
>       <right>5</right>
>       <wrong>0</wrong>
>       <ignores>0</ignores>
>       <exceptions>0</exceptions>
>     </counts>
>     <runTimeInMillis>10858</runTimeInMillis>
>     <relativePageName>SuiteSetUp</relativePageName>
>     <pageHistoryLink>XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.SuiteSetUp?pageHistory&amp;resultDate=20140828152108</pageHistoryLink>  
> WARNING: error registered in test system [Invocation of method 'getTestResult' in  class fitnesse.reporting.history.SuiteXmlReformatter threw exception java.lang.NullPointerException at
> suiteXML.vm[line 16, column 35]]
> org.apache.velocity.exception.MethodInvocationException: Invocation of method 'getTestResult' in  class fitnesse.reporting.history.SuiteXmlReformatter threw exception java.lang.NullPointerEx
> ception at suiteXML.vm[line 16, column 35]
>         at org.apache.velocity.runtime.parser.node.ASTMethod.handleInvocationException(ASTMethod.java:243)
>         at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:187)
>         at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:280)
>         at org.apache.velocity.runtime.parser.node.ASTReference.value(ASTReference.java:567)
>         at org.apache.velocity.runtime.parser.node.ASTExpression.value(ASTExpression.java:71)
>         at org.apache.velocity.runtime.parser.node.ASTSetDirective.render(ASTSetDirective.java:142)
>         at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
>         at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:420)
>         at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
>         at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
>         at org.apache.velocity.Template.merge(Template.java:356)
>         at org.apache.velocity.Template.merge(Template.java:260)
>         at fitnesse.reporting.history.SuiteXmlReformatter.close(SuiteXmlReformatter.java:57)
>         at fitnesse.testrunner.CompositeFormatter.close(CompositeFormatter.java:29)
>         at fitnesse.testrunner.MultipleTestsRunner.allTestingComplete(MultipleTestsRunner.java:75)
>         at fitnesse.testrunner.MultipleTestsRunner.executeTestPages(MultipleTestsRunner.java:70)
>         at fitnesse.responders.run.TestResponder.performExecution(TestResponder.java:273)
>         at fitnesse.responders.run.TestResponder.doExecuteTests(TestResponder.java:121)
>         at fitnesse.responders.run.TestResponder.doSending(TestResponder.java:109)
>         at fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:70)
>         at fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:25)
>         at fitnesse.http.MockResponseSender$OutputStreamSender.doSending(MockResponseSender.java:57)
>         at fitnesse.FitNesse.executeSingleCommand(FitNesse.java:89)
>         at fitnesseMain.FitNesseMain.executeSingleCommand(FitNesseMain.java:118)
>         at fitnesseMain.FitNesseMain.launch(FitNesseMain.java:92)
>         at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:72)
>         at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:51)
>         at fitnesseMain.FitNesseMain.main(FitNesseMain.java:35)
> Caused by: java.lang.NullPointerException
>         at fitnesse.reporting.history.SuiteXmlReformatter.getTestResult(SuiteXmlReformatter.java:70)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>         at java.lang.reflect.Method.invoke(Unknown Source)
>         at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:395)
>         at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:384)
>         at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:173)
>         ... 26 more

**Comment by konstantinvlasenko** [comment]
I still has this (or similar) issue in the latest release:
``java
[12:23:15]WARNING: error registered in test system [Invocation of method 'getTestResult' in  class fitnesse.reporting.history.SuiteXmlReformatter threw exception java.lang.NullPointerException at suiteXML.vm[line 16, column 35]]
[12:23:15]org.apache.velocity.exception.MethodInvocationException: Invocation of method 'getTestResult' in  class fitnesse.reporting.history.SuiteXmlReformatter threw exception java.lang.NullPointerException at suiteXML.vm[line 16, column 35]
[12:23:15]	at org.apache.velocity.runtime.parser.node.ASTMethod.handleInvocationException(ASTMethod.java:243)
[12:23:15]	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:187)
[12:23:15]	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:280)
[12:23:15]	at org.apache.velocity.runtime.parser.node.ASTReference.value(ASTReference.java:567)
[12:23:15]	at org.apache.velocity.runtime.parser.node.ASTExpression.value(ASTExpression.java:71)
[12:23:15]	at org.apache.velocity.runtime.parser.node.ASTSetDirective.render(ASTSetDirective.java:142)
[12:23:15]	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
[12:23:15]	at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:420)
[12:23:15]	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
[12:23:15]	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
[12:23:15]	at org.apache.velocity.Template.merge(Template.java:356)
[12:23:15]	at org.apache.velocity.Template.merge(Template.java:260)
[12:23:15]	at fitnesse.reporting.history.SuiteXmlReformatter.close(SuiteXmlReformatter.java:51)
[12:23:16]	at fitnesse.testrunner.CompositeFormatter.close(CompositeFormatter.java:29)
[12:23:16]	at fitnesse.testrunner.MultipleTestsRunner.allTestingComplete(MultipleTestsRunner.java:70)
[12:23:16]	at fitnesse.testrunner.MultipleTestsRunner.executeTestPages(MultipleTestsRunner.java:65)
[12:23:16]	at fitnesse.responders.run.SuiteResponder.performExecution(SuiteResponder.java:283)
[12:23:16]	at fitnesse.responders.run.SuiteResponder.doExecuteTests(SuiteResponder.java:129)
[12:23:16]	at fitnesse.responders.run.SuiteResponder.doSending(SuiteResponder.java:117)
[12:23:16]	at fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:70)
[12:23:16]	at fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:25)
[12:23:16]	at fitnesse.http.MockResponseSender$OutputStreamSender.doSending(MockResponseSender.java:57)
[12:23:16]	at fitnesse.FitNesse.executeSingleCommand(FitNesse.java:89)
[12:23:16]	at fitnesseMain.FitNesseMain.executeSingleCommand(FitNesseMain.java:115)
[12:23:16]	at fitnesseMain.FitNesseMain.launch(FitNesseMain.java:89)
[12:23:16]	at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:69)
[12:23:16]	at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:48)
[12:23:16]	at fitnesseMain.FitNesseMain.main(FitNesseMain.java:32)
[12:23:16]Caused by: java.lang.NullPointerException
[12:23:16]	at fitnesse.reporting.history.SuiteXmlReformatter.getTestResult(SuiteXmlReformatter.java:64)
[12:23:16]	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:23:16]	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[12:23:16]	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12:23:16]	at java.lang.reflect.Method.invoke(Unknown Source)
[12:23:16]	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:395)
[12:23:16]	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:384)
[12:23:16]	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:173)
``

**Comment by konstantinvlasenko** [comment]
Please, re-open this issue.
I'll use my [workaround](https://github.com/konstantinvlasenko/fitnesse/blob/master/src/fitnesse/reporting/history/SuiteXmlReformatter.java#L65-L67) for a while in my fork.
But I am going to spend some time to fix an original issue.
