### ISSUE TITLE
Number Format Exception In Fitness 

### ISSUE THREAD

**Issue by aravsri** [unclebob/fitnesse#533]
I have run a fitness test case and i see the following in the console

java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
        at java.lang.Integer.parseInt(Integer.java:470)
        at java.lang.Integer.parseInt(Integer.java:499)
        at fitnesse.slim.SlimClient.invokeAndGetResponse(SlimClient.java:74)
        at fitnesse.responders.run.slimResponder.SlimTestSystem.processTablesAndGetHtml(SlimTestSystem.java:298)
        at fitnesse.responders.run.slimResponder.SlimTestSystem.processAllTablesOnPage(SlimTestSystem.java:283)
        at fitnesse.responders.run.slimResponder.SlimTestSystem.runTestsAndGenerateHtml(SlimTestSystem.java:227)
        at fitnesse.responders.run.MultipleTestsRunner.executeTestSystemPages(MultipleTestsRunner.java:140)
        at fitnesse.responders.run.MultipleTestsRunner.startTestSystemAndExecutePages(MultipleTestsRunner.java:120)
        at fitnesse.responders.run.MultipleTestsRunner.executePagesInTestSystem(MultipleTestsRunner.java:106)
        at fitnesse.responders.run.MultipleTestsRunner.internalExecuteTestPages(MultipleTestsRunner.java:86)
        at fitnesse.responders.run.MultipleTestsRunner.executeTestPages(MultipleTestsRunner.java:58)
        at fitnesse.responders.run.SuiteResponder.performExecution(SuiteResponder.java:47)
        at fitnesse.responders.run.TestResponder.doSending(TestResponder.java:45)
        at fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:67)
        at fitnesse.responders.ChunkingResponder.access$000(ChunkingResponder.java:17)
        at fitnesse.responders.ChunkingResponder$RespondingRunnable.run(ChunkingResponder.java:106)
        at java.lang.Thread.run(Thread.java:662)

**Comment by amolenaar** [comment]
Closing issue due to lack of response.
