### ISSUE TITLE
Error Registered in System

### ISSUE THREAD

**Issue by KateDavis** [unclebob/fitnesse#582]
This is the same as Issue #512 

WARNING: error registered in test system [Connection reset by peer: socket write
 error]
java.net.SocketException: Connection reset by peer: socket write error
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(Unknown Source)
        at java.net.SocketOutputStream.write(Unknown Source)
        at fit.FitProtocol.writeSize(FitProtocol.java:29)
        at fit.FitProtocol.writeData(FitProtocol.java:21)
        at fit.FitProtocol.writeData(FitProtocol.java:16)
        at fitnesse.testsystems.fit.FitClient.send(FitClient.java:53)
        at fitnesse.testsystems.fit.FitTestSystem.runTests(FitTestSystem.java:52
)
        at fitnesse.testrunner.MultipleTestsRunner.executeTestSystemPages(Multip
leTestsRunner.java:175)
        at fitnesse.testrunner.MultipleTestsRunner.startTestSystemAndExecutePage
s(MultipleTestsRunner.java:103)
        at fitnesse.testrunner.MultipleTestsRunner.internalExecuteTestPages(Mult
ipleTestsRunner.java:88)
        at fitnesse.testrunner.MultipleTestsRunner.executeTestPages(MultipleTest
sRunner.java:70)
        at fitnesse.responders.run.TestResponder.performExecution(TestResponder.
java:274)
        at fitnesse.responders.run.TestResponder.doExecuteTests(TestResponder.ja
va:122)
        at fitnesse.responders.run.TestResponder$TestExecutor.execute(TestRespon
der.java:206)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.do
Invoke(UberspectImpl.java:395)
        at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.in
voke(UberspectImpl.java:384)
        at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.j
ava:173)
        at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTRefer
ence.java:280)
        at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTRefere
nce.java:369)
        at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.
java:342)
        at org.apache.velocity.runtime.directive.Parse.render(Parse.java:260)
        at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirect
ive.java:207)
        at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.
java:342)
        at org.apache.velocity.Template.merge(Template.java:356)
        at org.apache.velocity.Template.merge(Template.java:260)
        at fitnesse.html.template.HtmlPage.render(HtmlPage.java:81)
        at fitnesse.responders.run.TestResponder.doSending(TestResponder.java:10
8)
        at fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.
java:70)
        at fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:25)
        at fitnesse.FitNesseExpediter.sendResponse(FitNesseExpediter.java:100)
        at fitnesse.FitNesseExpediter.start(FitNesseExpediter.java:51)
        at fitnesse.FitNesseServer.serve(FitNesseServer.java:28)
        at fitnesse.FitNesseServer.serve(FitNesseServer.java:21)
        at fitnesse.socketservice.SocketService$ServerRunner.run(SocketService.j
ava:110)
        at java.lang.Thread.run(Unknown Source)
Output stream closed unexpectedly (Stop button pressed?) [Software caused connec
tion abort: socket write error]

I only get this when running large suites. Could there be a memory leak?

**Comment by amolenaar** [comment]
This normally happens when the SUT shuts down. Have you checked the logs of the SUT?

**Comment by konstantinvlasenko** [comment]
I am getting it as well on one of my Suite. It is not as large as others. So size is not an issue.
At the same time the test results xml file is not written correctly. So I have something like this (invalid XML):

``xml
<?xml version="1.0"?>
<testResults>
  <FitNesseVersion>v20150114</FitNesseVersion>
  <rootPath>AcceptanceTests.SuiteFolder.SuiteWord</rootPath>
    <result>
    <counts>
      <right>4</right>
      <wrong>0</wrong>
      <ignores>0</ignores>
      <exceptions>0</exceptions>
    </counts>
    <runTimeInMillis>7883</runTimeInMillis>
    <relativePageName>SuiteSetUp</relativePageName>
    <pageHistoryLink>AcceptanceTests.SuiteFolder.SuiteWord.SuiteSections.SuiteSetUp?pageHistory&amp;resultDate=20150205161101</pageHistoryLink>
``

**Comment by konstantinvlasenko** [comment]
Please, try this build http://s3.amazonaws.com/Vlasenko/Fitnesse/fitnesse-standalone.jar
It contains this [workaround](https://github.com/konstantinvlasenko/fitnesse/blob/master/src/fitnesse/reporting/history/SuiteXmlReformatter.java#L65-L68).

**Comment by amolenaar** [comment]
I added a catch all on the test runner (the code that fires up the test systems). It should catch any exception that comes from the test systems.
