### ISSUE TITLE
Saving a page fails while writing properties.xml - likely due to conflict with other JARs in classpath

### ISSUE THREAD

**Issue by f10f0bfbd87448** [unclebob/fitnesse#598]
I'm sorry, this ticket isn't very precise because I don't know exactly what is going on. When trying to save a page, FitNesse fails with this error message on stderr:
````
WARNING: Unable to handle request [Not supported: indent-number]
java.lang.IllegalArgumentException: Not supported: indent-number
        at org.apache.xalan.processor.TransformerFactoryImpl.setAttribute(TransformerFactoryImpl.java:576)
        at fitnesse.util.XmlUtil.xmlAsString(XmlUtil.java:123)
        at fitnesse.wiki.WikiPageProperties.toXml(WikiPageProperties.java:102)
        at fitnesse.wiki.fs.FileSystemPage$PropertiesFileVersion.getContent(FileSystemPage.java:342)
        at fitnesse.wiki.fs.SimpleFileVersionsController.makeVersion(SimpleFileVersionsController.java:75)
        at fitnesse.wiki.fs.ZipFileVersionsController.makeVersion(ZipFileVersionsController.java:101)
        at fitnesse.wiki.fs.FileSystemPage.commit(FileSystemPage.java:142)
        at fitnesse.wiki.WikiPageUtil.addPage(WikiPageUtil.java:58)
        at fitnesse.responders.editing.AddChildPageResponder.createChildPage(AddChildPageResponder.java:83)
        at fitnesse.responders.editing.AddChildPageResponder.createChildPageAndMakeResponse(AddChildPageResponder.java:65)
        at fitnesse.responders.editing.AddChildPageResponder.makeResponse(AddChildPageResponder.java:39)
        at fitnesse.FitNesseExpediter.createGoodResponse(FitNesseExpediter.java:136)
        at fitnesse.FitNesseExpediter.makeResponse(FitNesseExpediter.java:114)
        at fitnesse.FitNesseExpediter.start(FitNesseExpediter.java:50)
        at fitnesse.FitNesseServer.serve(FitNesseServer.java:28)
        at fitnesse.FitNesseServer.serve(FitNesseServer.java:21)
        at fitnesse.socketservice.SocketService$ServerRunner.run(SocketService.java:109)
        at java.lang.Thread.run(Thread.java:701)
````
Looking at the corresponding folder in FitNesse's wiki hierarchy, it turns out that ``properties.xml`` was not created and as a result, changes to the page can not be made (due to ``java.io.FileNotFoundException``).

The error disappears when I remove one of my fixture JARs from the classpath. Looking into said JAR, it turns out that it contains the ``org.apache.xalan`` package, version 2.7.1. This is what seems to be causing the problem.

Is this simply my fault and I have to fix the JAR?
I found a [related question on StackOverflow](http://stackoverflow.com/q/15134861) and they suggest changing the attribute name to have ``{http://xml.apache.org/xslt}`` as a prefix.

Could you please either tell me what I'm doing wrong or try to fix the issue? I guess **steps to reproduce** are to put a JAR containing Apache Xalan 2.7.1 into the classpath and try to save a page in the wiki.

Thanks in advance.

**Comment by amolenaar** [comment]
Ouch! Thanks for noting. It's been fixed now.

**Comment by f10f0bfbd87448** [comment]
Thanks!
