### ISSUE TITLE
Missing properties.xml in ErrorLogs results in exception and loss of logging

### ISSUE THREAD

**Issue by simonvanderveldt** [unclebob/fitnesse#638]
When the properties.xml from the ErrorLogs of a test isn't present FitNesse errors out with a file not found exception. This unfortunately also means there is no logging shown in the captured log from within FitNesse. IMHO this is a case that should be cathed.

```
[java] WARNING: error registered in test system [java.io.FileNotFoundException: .\FitNesseRoot\ErrorLogs\FrontPage\x\y\properties.xml (The system cannot find the file specified)]
[java] java.lang.RuntimeException: java.io.FileNotFoundException: .\FitNesseRoot\ErrorLogs\FrontPage\x\y\properties.xml (The system cannot find the file specified)
[java]     at fitnesse.wiki.fs.ZipFileVersionsController.makeZipVersion(ZipFileVersionsController.java:124)
[java]     at fitnesse.wiki.fs.ZipFileVersionsController.makeVersion(ZipFileVersionsController.java:90)
[java]     at fitnesse.wiki.fs.FileSystemPage.commit(FileSystemPage.java:135)
[java]     at fitnesse.reporting.CompositeExecutionLog.publish(CompositeExecutionLog.java:58)
[java]     at fitnesse.responders.run.TestResponder.performExecution(TestResponder.java:275)
[java]     at fitnesse.responders.run.TestResponder.doExecuteTests(TestResponder.java:121)
[java]     at fitnesse.responders.run.TestResponder$TestExecutor.execute(TestResponder.java:205)
[java]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[java]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[java]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[java]     at java.lang.reflect.Method.invoke(Method.java:606)
[java]     at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:395)
[java]     at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:384)
[java]     at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:173)
[java]     at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:280)
[java]     at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:369)
[java]     at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
[java]     at org.apache.velocity.runtime.directive.Parse.render(Parse.java:260)
[java]     at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
[java]     at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
[java]     at org.apache.velocity.Template.merge(Template.java:356)
[java]     at org.apache.velocity.Template.merge(Template.java:260)
[java]     at fitnesse.html.template.HtmlPage.render(HtmlPage.java:81)
[java]     at fitnesse.responders.run.TestResponder.doSending(TestResponder.java:107)
[java]     at fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:70)
[java]     at fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:25)
[java]     at fitnesse.FitNesseExpediter.sendResponse(FitNesseExpediter.java:100)
[java]     at fitnesse.FitNesseExpediter.start(FitNesseExpediter.java:51)
[java]     at fitnesse.FitNesseServer.serve(FitNesseServer.java:28)
[java]     at fitnesse.FitNesseServer.serve(FitNesseServer.java:21)
[java]     at fitnesse.socketservice.SocketService$ServerRunner.run(SocketService.java:110)
[java]     at java.lang.Thread.run(Thread.java:744)
[java] Caused by: java.io.FileNotFoundException: .\FitNesseRoot\ErrorLogs\FrontPage\x\y\properties.xml (The system cannot find the file specified)
[java]     at java.io.FileInputStream.open(Native Method)
[java]     at java.io.FileInputStream.<init>(FileInputStream.java:146)
[java]     at fitnesse.wiki.fs.ZipFileVersionsController.addToZip(ZipFileVersionsController.java:163)
[java]     at fitnesse.wiki.fs.ZipFileVersionsController.makeZipVersion(ZipFileVersionsController.java:121)
[java]     ... 31 more
```

**Comment by amolenaar** [comment]
I expect this will be fixed by #627, since that obsoletes the ErrorLogs page and puts all execution log information in the test history.

**Comment by simonvanderveldt** [comment]
Just to be sure, and for reference later:
If the execution logs are stored along with the test results they well be xml-files just like the test history files, right?
That would also mean that since the execution logs are no longer stored as a wiki page the properties.xml file wouldn't be necessary anymore, correct?

**Comment by amolenaar** [comment]
Yup
