### ISSUE TITLE
"Read timed out" killing Slim client with FitNesse v20150225

### ISSUE THREAD

**Issue by reprive** [unclebob/fitnesse#653]
I've built the last FitNesse release 20150225 and am getting random Read Timed out exceptions on Slim tests, which completely kill the test pages (they don't get finished - not even with errors/exceptions). The status bar becomes "Testing was interrupted and results are incomplete. Test Pages: 0 right, 0 wrong, 0 ignored, 0 exceptions     Assertions: 0 right, 0 wrong, 0 ignored, 0 exceptions (11.499 seconds)".

This happens on tests that work perfectly on v20150114. I haven't been able to figure out what exactly causes this, but the tests that have the issue are not very fast (driving browsers). 

Has a new timeout value been introduced recently? If so how can I set that to a larger value?

I see in the log: 
SEVERE: Killing slim clint as exception occured:java.net.SocketTimeoutException: Read timed out
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at java.io.BufferedInputStream.fill(Unknown Source)
        at java.io.BufferedInputStream.read1(Unknown Source)
        at java.io.BufferedInputStream.read(Unknown Source)
        at java.io.FilterInputStream.read(Unknown Source)
        at util.StreamReader$2.read(StreamReader.java:218)
        at util.StreamReader.readUntilFinished(StreamReader.java:140)
        at util.StreamReader.preformRead(StreamReader.java:119)
        at util.StreamReader.readBytes(StreamReader.java:77)
        at util.StreamReader.read(StreamReader.java:70)
        at fitnesse.slim.SlimStreamReader.getLengthToRead(SlimStreamReader.java:34)
        at fitnesse.slim.SlimStreamReader.getSlimMessage(SlimStreamReader.java:55)
        at fitnesse.testsystems.slim.SlimCommandRunningClient.invokeAndGetResponse(SlimCommandRunningClient.java:168)
        at fitnesse.testsystems.slim.SlimTestSystem.processTable(SlimTestSystem.java:124)
        at fitnesse.testsystems.slim.HtmlSlimTestSystem.processAllTablesOnPage(HtmlSlimTestSystem.java:48)
        at fitnesse.testsystems.slim.SlimTestSystem.runTests(SlimTestSystem.java:101)
        at fitnesse.testrunner.MultipleTestsRunner.executeTestSystemPages(MultipleTestsRunner.java:171)
        at fitnesse.testrunner.MultipleTestsRunner.startTestSystemAndExecutePages(MultipleTestsRunner.java:89)
        at fitnesse.testrunner.MultipleTestsRunner.internalExecuteTestPages(MultipleTestsRunner.java:77)
        at fitnesse.testrunner.MultipleTestsRunner.executeTestPages(MultipleTestsRunner.java:63)
        at fitnesse.responders.run.SuiteResponder.performExecution(SuiteResponder.java:306)
        at fitnesse.responders.run.SuiteResponder.doExecuteTests(SuiteResponder.java:139)
        at fitnesse.responders.run.SuiteResponder$TestExecutor.execute(SuiteResponder.java:222)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:395)
        at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:384)
        at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:173)
        at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:280)
        at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:369)
        at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
        at org.apache.velocity.runtime.directive.Parse.render(Parse.java:260)
        at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
        at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
        at org.apache.velocity.Template.merge(Template.java:356)
        at org.apache.velocity.Template.merge(Template.java:260)
        at fitnesse.html.template.HtmlPage.render(HtmlPage.java:81)
        at fitnesse.responders.run.SuiteResponder.doSending(SuiteResponder.java:115)
        at fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:70)
        at fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:25)
        at fitnesse.FitNesseExpediter.sendResponse(FitNesseExpediter.java:102)
        at fitnesse.FitNesseExpediter.start(FitNesseExpediter.java:52)
        at fitnesse.FitNesseServer.serve(FitNesseServer.java:28)
        at fitnesse.FitNesseServer.serve(FitNesseServer.java:21)
        at fitnesse.socketservice.SocketService$ServerRunner.run(SocketService.java:122)
        at java.lang.Thread.run(Unknown Source)

**Comment by six42** [comment]
Define the variable "slim.timeout" either on your test page or in the fitnesse properties file.
Give the value in seconds. Default is 10.

Please let us know if this helped.

**Comment by fhoeben** [comment]
I had the same problem, setting slim.timeout fixed it for me

**Comment by reprive** [comment]
Yes, setting the slim.timeout variable fixed it. Thanks!
