### ISSUE TITLE
Empty Cell value is null instead of empty string

### ISSUE THREAD

**Issue by davidmagill** [unclebob/fitnesse#686]
The previous versions passed empty cells as a String.  It is now passing those values as null... this is causing several of our tables to break and throw null pointer exceptions.

**Comment by davidmagill** [comment]
Stack trace for fitnesse.

	at fitnesse.slim.fixtureInteraction.DefaultInteraction.methodInvoke(DefaultInteraction.java:16)
	at fitnesse.slim.MethodExecutor.callMethod(MethodExecutor.java:44)
	at fitnesse.slim.MethodExecutor.invokeMethod(MethodExecutor.java:31)
	at fitnesse.slim.MethodExecutor.findAndInvoke(MethodExecutor.java:53)
	at fitnesse.slim.FixtureMethodExecutor.execute(FixtureMethodExecutor.java:20)
	at fitnesse.slim.StatementExecutor.getMethodExecutionResult(StatementExecutor.java:123)
	at fitnesse.slim.StatementExecutor.call(StatementExecutor.java:101)
	at fitnesse.slim.instructions.CallInstruction.executeInternal(CallInstruction.java:35)
	at fitnesse.slim.instructions.Instruction.execute(Instruction.java:30)
	at fitnesse.slim.ListExecutor$Executive.executeStatement(ListExecutor.java:49)
	at fitnesse.slim.ListExecutor$Executive.executeStatements(ListExecutor.java:43)
	at fitnesse.slim.ListExecutor.execute(ListExecutor.java:83)
	at fitnesse.slim.SlimServer.executeInstructions(SlimServer.java:87)
	at fitnesse.slim.SlimServer.processOneSetOfInstructions(SlimServer.java:80)
	at fitnesse.slim.SlimServer.tryProcessInstructions(SlimServer.java:59)
	at fitnesse.slim.SlimServer.serve(SlimServer.java:45)
	at fitnesse.slim.SlimService.handle(SlimService.java:184)
	at fitnesse.slim.SlimService.acceptOne(SlimService.java:192)
	at fitnesse.slim.SlimService.accept(SlimService.java:154)
	at fitnesse.slim.SlimService.startWithFactory(SlimService.java:75)
	at fitnesse.slim.SlimService.main(SlimService.java:56)
