### ISSUE TITLE
SuiteHistoryFormatter - NullPointerException

### ISSUE THREAD

**Issue by phgr100x** [unclebob/fitnesse#736]
When you launch a Suite Test on wiki and then you click on "Stop Test" button, you have the following stacktrace :

 java.lang.NullPointerException
        at fitnesse.reporting.history.SuiteHistoryFormatter.testComplete(SuiteHistoryFormatter.java:86)
        at fitnesse.reporting.history.SuiteHistoryFormatter.testComplete(SuiteHistoryFormatter.java:28)
        at fitnesse.testsystems.CompositeTestSystemListener.testComplete(CompositeTestSystemListener.java:40)
        at fitnesse.testrunner.MultipleTestsRunner$InternalTestSystemListener.testComplete(MultipleTestsRunner.java:205)
        at fitnesse.testrunner.MultipleTestsRunner$InternalTestSystemListener.testComplete(MultipleTestsRunner.java:187)
        at fitnesse.testsystems.CompositeTestSystemListener.testComplete(CompositeTestSystemListener.java:40)
        at fitnesse.testsystems.slim.SlimTestSystem.testComplete(SlimTestSystem.java:205)
        at fitnesse.testsystems.slim.SlimTestSystem.runTests(SlimTestSystem.java:105)
        at fitnesse.testrunner.MultipleTestsRunner.executeTestSystemPages(MultipleTestsRunner.java:169)
        at fitnesse.testrunner.MultipleTestsRunner.startTestSystemAndExecutePages(MultipleTestsRunner.java:89)
        at fitnesse.testrunner.MultipleTestsRunner.internalExecuteTestPages(MultipleTestsRunner.java:77)
        at fitnesse.testrunner.MultipleTestsRunner.executeTestPages(MultipleTestsRunner.java:63)
        at fitnesse.responders.run.SuiteResponder.performExecution(SuiteResponder.java:309)
        at fitnesse.responders.run.SuiteResponder.doExecuteTests(SuiteResponder.java:144)
        at fitnesse.responders.run.SuiteResponder$TestExecutor.execute(SuiteResponder.java:225)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:395)
        at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:384)
        at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:173)
        at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:280)
        at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:369)
        at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
        at org.apache.velocity.runtime.directive.Parse.render(Parse.java:260)
        at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
        at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
        at org.apache.velocity.Template.merge(Template.java:356)
        at org.apache.velocity.Template.merge(Template.java:260)
        at fitnesse.html.template.HtmlPage.render(HtmlPage.java:81)
        at fitnesse.responders.run.SuiteResponder.doSending(SuiteResponder.java:120)
        at fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:70)
        at fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:25)
        at fitnesse.FitNesseExpediter.sendResponse(FitNesseExpediter.java:102)
        at fitnesse.FitNesseExpediter.start(FitNesseExpediter.java:52)
        at fitnesse.FitNesseServer.serve(FitNesseServer.java:28)
        at fitnesse.FitNesseServer.serve(FitNesseServer.java:21)
        at fitnesse.socketservice.SocketService$ServerRunner.run(SocketService.java:122)
        at java.lang.Thread.run(Thread.java:745)

**Comment by amolenaar** [comment]
Merged #736. That should fix it.
