### ISSUE TITLE
NullPointerException when running FitNesse.SuiteAcceptanceTests

### ISSUE THREAD

**Issue by haroon-sheikh** [unclebob/fitnesse#856]
```bash
__EXCEPTION__:java.lang.NullPointerException
	at fitnesse.fixtures.PageCreator.valid(PageCreator.java:20) [fitnesse-20151230.jar]
	at fitnesse.fixtures.PageDriver.createPageWithContent(PageDriver.java:40) [fitnesse-20151230.jar]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_55]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_55]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_55]
	at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_55]
	at fitnesse.slim.fixtureInteraction.DefaultInteraction.methodInvoke(DefaultInteraction.java:81) [fitnesse-20151230.jar]
	at fitnesse.slim.MethodExecutor.callMethod(MethodExecutor.java:57) [fitnesse-20151230.jar]
	at fitnesse.slim.MethodExecutor.invokeMethod(MethodExecutor.java:38) [fitnesse-20151230.jar]
	at fitnesse.slim.MethodExecutor.findAndInvoke(MethodExecutor.java:72) [fitnesse-20151230.jar]
	at fitnesse.slim.LibraryMethodExecutor.execute(LibraryMethodExecutor.java:18) [fitnesse-20151230.jar]
	at fitnesse.slim.StatementExecutor.getMethodExecutionResult(StatementExecutor.java:135) [fitnesse-20151230.jar]
	at fitnesse.slim.StatementExecutor.call(StatementExecutor.java:108) [fitnesse-20151230.jar]
	at fitnesse.slim.instructions.CallInstruction.executeInternal(CallInstruction.java:35) [fitnesse-20151230.jar]
	at fitnesse.slim.instructions.Instruction.execute(Instruction.java:29) [fitnesse-20151230.jar]
	at fitnesse.slim.ListExecutor$Executive.executeStatement(ListExecutor.java:49) [fitnesse-20151230.jar]
	at fitnesse.slim.ListExecutor$Executive.executeStatements(ListExecutor.java:43) [fitnesse-20151230.jar]
	at fitnesse.slim.ListExecutor.execute(ListExecutor.java:85) [fitnesse-20151230.jar]
	at fitnesse.slim.SlimServer.executeInstructions(SlimServer.java:84) [fitnesse-20151230.jar]
	at fitnesse.slim.SlimServer.processOneSetOfInstructions(SlimServer.java:77) [fitnesse-20151230.jar]
	at fitnesse.slim.SlimServer.tryProcessInstructions(SlimServer.java:64) [fitnesse-20151230.jar]
	at fitnesse.slim.SlimServer.serve(SlimServer.java:49) [fitnesse-20151230.jar]
	at fitnesse.slim.SlimService.handle(SlimService.java:154) [fitnesse-20151230.jar]
	at fitnesse.slim.SlimService.acceptOne(SlimService.java:162) [fitnesse-20151230.jar]
	at fitnesse.slim.SlimService.accept(SlimService.java:124) [fitnesse-20151230.jar]
	at fitnesse.slim.SlimService.startWithFactory(SlimService.java:76) [fitnesse-20151230.jar]
	at fitnesse.slim.SlimService.main(SlimService.java:56) [fitnesse-20151230.jar]
```
Can someone please advise?

**Comment by amolenaar** [comment]
What did you do to trigger this exception?

**Comment by haroon-sheikh** [comment]
@amolenaar this is what I get when running the fitnesse SuiteAcceptanceTests.

**Comment by haroon-sheikh** [comment]
@amolenaar it looks like its throwing an exception when the fitlibrary dependency is included

```bash
<dependency>
    <groupId>com.github.dbfit</groupId>
    <artifactId>fitlibrary</artifactId>
    <version>20091020</version>
</dependency>
```

The above was included as part of `dbfit` and Hence failing the suite tests.

Any idea why that might be?

**Comment by amolenaar** [comment]
I don't know. Is fitlibrary shadowing files from FitNesse?

**Comment by haroon-sheikh** [comment]
It looks like it https://github.com/dbfit/dbfit

**Comment by amolenaar** [comment]
Can this issue be closed?

**Comment by haroon-sheikh** [comment]
I guess its still an issue, I think for now I've just excluded the db fit dependency. But I'm happy for you to close if it's not a fitnesse related issue.

**Comment by amolenaar** [comment]
Okay. Thanks. Isn't there a more recent version fo DBFit available?
