### ISSUE TITLE
MarkupHashTable produce error when need to be mapped in Map<String, String> in newest version of fitnesse

### ISSUE THREAD

**Issue by sasastarcevic** [unclebob/fitnesse#892]
Hi All,

Right now we use fitnesse version: 20140901 in our project and with this version we can use step like:
`|and |set customer capabilities !{CAP2:100000, CAP2:1}|`

In java we use:
`@DomainStep("(?si)set customer capabilities (.+)")
public void setCustomerCapabilities(Map<String, String> capability) {`

But from fitnesse version: 20150424 up to newest 20151230 (http://www.fitnesse.org/FitNesseDownload of course we have checked release notes, but we haven't found solution), same step will fail, with error:
`Caused by: java.lang.IllegalArgumentException: argument type mismatch`

Of course we can bypass this (with parsing and creating object), but do we have some better solution?

Many thanks,
Sasa

**Comment by amolenaar** [comment]
Hi,

Let me check on this.

**Comment by amolenaar** [comment]
What does the `@DomainStep` annotation do? It is not part of FitNesse.

**Comment by sasastarcevic** [comment]
Hi,

We use @DomainStep annotation while creating wiki steps in Java classes, so that we can call java methods from fitnesse wiki pages.

It is used in combination with annotation: @DomainSteps

For example, we have class: CapabilitySteps and we need to have annotatio like:

@DomainSteps
public class CapabilitySteps {
...
and in this class we have method:

@DomainStep("(?si)set customer capabilities (.+)") 
public void setCustomerCapabilities(Map<String, String> capability) {
.....

And when we have class like this, then we can call this method from fitnesse wiki page, like:
|then |set customer capabilities !{CAP_1:100000, CAP_2:0}  |
So this is not working with new version of fitnesse.

Imports for DomainStep:
import org.givwenzen.annotations.DomainStep;
import org.givwenzen.annotations.DomainSteps;

Sorry for late response.
BR,
Sasa

**Comment by amolenaar** [comment]
Is this a problem in the DomainStep maybe? I added some tests in FitNesse and it seems to work fine.

**Comment by s-ivanova** [comment]
We use givwenzen - plugin to Fitnesse. Everything was working fine with 20140901 version. We tried the newest version 20161106 and the issue still persist:
Caused by: java.lang.IllegalArgumentException: argument type mismatch

This is visible in the log:
WARNING: An error occured while fulfilling user request [fitnesse.http.HttpException: The request string is malformed and can not be parsed]
java.util.concurrent.ExecutionException: fitnesse.http.HttpException: The request string is malformed and can not be parsed
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at fitnesse.FitNesseExpediter.makeResponse(FitNesseExpediter.java:105)
        at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:58)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: fitnesse.http.HttpException: The request string is malformed and can not be parsed
        at fitnesse.http.Request.checkRequestLine(Request.java:159)
        at fitnesse.http.Request.readAndParseRequestLine(Request.java:73)
        at fitnesse.http.Request.parse(Request.java:61)
        at fitnesse.FitNesseExpediter$1.call(FitNesseExpediter.java:102)
        at fitnesse.FitNesseExpediter$1.call(FitNesseExpediter.java:99)

**Comment by janakijayasree** [comment]
hi i am using fitnesse-standalone latest ersion jar when i starting fitnesse on port:xxxx i am getting this error after taking long time time.even my test results are showing nothing.Please help me in this how to solve issue in connecting to port
An error occured while fulfilling user request [fitnesse.http.HttpException: The request string is malformed and can not be parsed]
java.util.concurrent.ExecutionException: fitnesse.http.HttpException: The request string is malformed and can not be parsed
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at fitnesse.FitNesseExpediter.makeResponse(FitNesseExpediter.java:105)
        at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:58)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown
