### ISSUE TITLE
Cannot load SqlServer database driver com.microsoft.sqlserver.jdbc.SQLServerDriver. Is the JDBC driver on the classpath?

### ISSUE THREAD

**Issue by maheshrecr** [unclebob/fitnesse#926]
Hello Friends,

I am newbie to dbfit, i have simple connection test as below

!path lib\*.jar
!|Import|
|fitnesse.fixtures|

!|dbfit.SqlServerTest|

When i execute test, getting below error

java.lang.Error: Cannot load SqlServer database driver com.microsoft.sqlserver.jdbc.SQLServerDriver. Is the JDBC driver on the classpath?
	at dbfit.api.DbEnvironmentFactory$EnvironmentDescriptor.checkDriver(DbEnvironmentFactory.java:45)
	at dbfit.api.DbEnvironmentFactory$EnvironmentDescriptor.createEnvironmentInstance(DbEnvironmentFactory.java:60)
	at dbfit.api.DbEnvironmentFactory.createEnvironmentInstance(DbEnvironmentFactory.java:102)
	at dbfit.api.DbEnvironmentFactory.newEnvironmentInstance(DbEnvironmentFactory.java:106)
	at dbfit.SqlServerTest.(SqlServerTest.java:5)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at fit.FixtureClass.newInstance(FixtureClass.java:24)
	at fit.FixtureLoader.instantiateFixture(FixtureLoader.java:62)
	at fit.FixtureLoader.instantiateFirstValidFixtureClass(FixtureLoader.java:84)
	at fit.FixtureLoader.disgraceThenLoad(FixtureLoader.java:44)
	at fit.Fixture.loadFixture(Fixture.java:142)
	at fit.Fixture.getLinkedFixtureWithArgs(Fixture.java:134)
	at fit.Fixture.interpretFollowingTables(Fixture.java:120)
	at fit.Fixture.interpretTables(Fixture.java:107)
	at fit.Fixture.doTables(Fixture.java:81)
	at fit.FitServer.process(FitServer.java:81)
	at fit.FitServer.run(FitServer.java:56)
	at fit.FitServer.main(FitServer.java:41)
Caused by: java.lang.ClassNotFoundException: com.microsoft.sqlserver.jdbc.SQLServerDriver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at dbfit.api.DbEnvironmentFactory$EnvironmentDescriptor.checkDriver(DbEnvironmentFactory.java:43)

Anyone can help me to resolve this please?

Cheers

**Comment by mgaertne** [comment]
Did you put the SQL-driver on the classpath?

Best
Markus

Save our Scrum: http://leanpub.com/saveourscrum
-- 
Dipl.-Inform. Markus Gaertner
Author of ATDD by Example - A Practical Guide to Acceptance Test-Driven
Development

http://www.shino.de/blog
http://www.mgaertne.de
http://www.it-agile.de
Twitter: @mgaertne

**Comment by maheshrecr** [comment]
My Sql Driver is in Fitnesse folder under lib directory.

Do i have to put that in the CLASSPATH?

**Comment by maheshrecr** [comment]
Default JDBC driver camw with dbfit didn't work, i downloaded new versions from microsoft site and kept them in the fitnesse\lib folder and it worked.

Thanks.
