### ISSUE TITLE
Release 20160618 requires Java 7? (java.lang.UnsupportedClassVersionError: fitnesseMain/FitNesseMain : Unsupported major.minor version 51.0)

### ISSUE THREAD

**Issue by dubaaron** [unclebob/fitnesse#969]
Trying to run fitnesse, I get:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: fitnesseMain/FitNesseMain : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
Could not find the main class: fitnesseMain.FitNesseMain. Program will exit.
```
From what I can tell, this means that it requires Java 7 to run.  Is that correct?
I have version 1.6:
```
java -showversion
java version "1.6.0_38"
OpenJDK Runtime Environment (IcedTea6 1.13.10) (rhel-1.13.10.0.el6_7-x86_64)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)
```
ON the page at http://fitnesse.org/FitNesseDownload it states that 

> FitNesse requires version 1.6 or later of the Java Runtime Environment (JRE). 

Java 1.6 is equivalent to Java SE 6.0, which is major version 50, I believe.
> Java SE 9 = 53,
> Java SE 8 = 52,
> Java SE 7 = 51,
> Java SE 6.0 = 50,
> Java SE 5.0 = 49,
> JDK 1.4 = 48,
> JDK 1.3 = 47,
> JDK 1.2 = 46,
> JDK 1.1 = 45
(Source: [Wikipedia)](https://en.wikipedia.org/wiki/Java_class_file#General_layout)

So, if this is the case, then I guess the download page needs updating?

**Comment by woodybrood** [comment]
Yes. We need to update that. I think the last two releases are Java 7 and up.

**Comment by woodybrood** [comment]
I just pushed an update to the FitNesse.org wiki. It might take a bit to update.

**Comment by dubaaron** [comment]
Alright, thanks for the clarification and update. : )
