### ISSUE TITLE
NoClassDefFoundError when running fitnesse tests through jenkins

### ISSUE THREAD

**Issue by michaelburns138** [unclebob/fitnesse#979]
I am trying to configure fitnesse to run through jenkins but the build fails and the fitnesse server never starts. 

I get the following error: 
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/velocity/context/Context
at fitnesse.FitNesseContext.<init>(FitNesseContext.java:83)
at fitnesse.ContextConfigurator.makeFitNesseContext(ContextConfigurator.java:125)
at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:65)
at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:54)
at fitnesseMain.FitNesseMain.main(FitNesseMain.java:34)
Caused by: java.lang.ClassNotFoundException: org.apache.velocity.context.Context

Fitnesse runs locally fine but not on through the jenkins fitnesse plugin.

I am using the fitnesse-20150814.jar.

Any help would be great thanks.

**Comment by amolenaar** [comment]
You're using the fitnesse jar only. It's missing its dependencies. You either want to use fitnesse-standalone instead or use a build tool like Maven or Gradle to take care of the dependencies.

I would suggest you'll do the latter (use Maven or Gradle) since that means that the build procedures can be kept and versioned with your test suite and code.
