### ISSUE TITLE
"WARNING: An error occured while fulfilling user request" in Firefox

### ISSUE THREAD

**Issue by johnnybaloney** [unclebob/fitnesse#981]
happens in release: **20160618** and **20160515**
different message in release: **20151230**

I'm following the guide on [FitNesse website](http://fitnesse.org/FitNesseDownload). Starting FitNesse for the first time:
````
$ java -jar fitnesse-standalone.jar -p 8080
````

After opening the home page (http://localhost:8080/) I get the following periodically:
````
WARNING: An error occured while fulfilling user request [fitnesse.http.HttpException: The request string is malformed and can not be parsed]
java.util.concurrent.ExecutionException: fitnesse.http.HttpException: The request string is malformed and can not be parsed
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at fitnesse.FitNesseExpediter.makeResponse(FitNesseExpediter.java:107)
	at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: fitnesse.http.HttpException: The request string is malformed and can not be parsed
	at fitnesse.http.Request.checkRequestLine(Request.java:159)
	at fitnesse.http.Request.readAndParseRequestLine(Request.java:73)
	at fitnesse.http.Request.parse(Request.java:61)
	at fitnesse.FitNesseExpediter$1.call(FitNesseExpediter.java:104)
	at fitnesse.FitNesseExpediter$1.call(FitNesseExpediter.java:101)
	... 4 more
````

This is what I see when I open the page in **Firefox 48.0**. When I open the page in **Chrome 52.0.2743.116 (64-bit)** I don't get any warning.

It seems that it gets triggered by hovering over the top menu buttons (Edit, Add, Tools) but I cannot see any network traffic in the developer tools of either browser. However, wireshark shows `400 Bad Request` and TCP RST flag sent:

![fitnesse-wireshark-tcp1](https://cloud.githubusercontent.com/assets/13626025/19471811/acd31c92-951c-11e6-9f1e-c2cdae0299cd.png)

In release **20151230** the behaviour is similar (no warnings when opening in Chrome) but the content of the message is:
````
Output stream closed unexpectedly: Broken pipe (Stop button pressed?)
````

**Comment by amolenaar** [comment]
Hi,

Does this result in functional errors in the application? 

I've seen an issue on this subject before. After investigation, it appeared Firefox was opening connections, but not sending any data.

There is a related issue, although I can not find it right now.

**Comment by johnnybaloney** [comment]
Hi,

I don't think so, it seems to be just noise in the log which I deemed necessary to investigate before actually using the tool. I didn't find anything related in this bug tracker when I encountered the issue for the first time hence this report.

**Comment by jediwhale** [comment]
Probably related to this but I haven't been able to narrow it down to an actual cause:
https://support.mozilla.org/en-US/kb/how-stop-firefox-making-automatic-connections

**Comment by amolenaar** [comment]
I can't find any reference either :/

FitNesse will shut down a connection if no request has been received within a reasonable timeframe, 10 seconds by default.
